#! perl

=head1 NAME

answerpassword - fills yubikey otp token ssh password prompts for good

=head1 SYNOPSIS

   urxvt -pe answerpassword

=head1 DESCRIPTION

FIXME

=cut

my $tokens_file='/home/user/.yubitokens';
my $password='prefixed-password';
my $prompt_seen=0;

sub get_token() {
	my $h;

	unless (open $h, "<:encoding(utf8)", $tokens_file) {
		warn("Could not open file '$tokens_file': $!");
		return undef,0;
	}

	my @lines=<$h>;

	close $h;

	if ($#lines) {
		my $token=shift @lines;

		unless (open $h, ">:encoding(utf8)", $tokens_file) {
			warn("Could not open file '$tokens_file': $!");
			return $token, $#lines;
		}

		print $h join('',@lines);

		close $h;
		return $token, $#lines;
	}
	return undef,0;
}

sub on_add_lines {
   my ($self, $string) = @_;

   if(($string eq "user\@remotehost's password: ") && ($prompt_seen==0)) {
	   $prompt_seen=1;
	   my ($token, $count) = get_token();
	   if ($token) {
		   msg($self, 'Entering Yubikey OTP.', $count);
		   my $octets = $self->locale_encode($password.$token);
		   $self->tt_write($octets);
	   } else {
		   msg($self, 'Failed entering.', 0);
	   }
   }
   $self->scr_add_lines($string);

   1;
}

sub msg {
	my ($self, $message, $count) = @_;

	my $overlay = $self->overlay (-26, 1, 23, 2, urxvt::OVERLAY_RSTYLE, 2);

	$overlay->set (1, 0, $message);

	if ($count>0) {
		$overlay->set (1, 1, "$count token".($count>1?'s':'')." left.");
	} else {
		$overlay->set (1, 1, "No more tokens. :(");
	}

	$self->{timer} = urxvt::timer->new->after (6)->cb (sub {
		delete $self->{timer};
		undef $overlay;
	});

	1;
}

sub on_start {
	my ($self) = @_;

	my $octets = $self->locale_encode("ssh <to-a-yubikeyed-machine>\n");
	$self->tt_write ($octets);

	()
}

